import '../modal/product_modal.dart';

List<Product> products = [
  Product(
    id: 1,
    name: "Veggie_pizza",
    price: 1000,
    image: "assets/images/veggie_pizza.jpg",
    Quantity: 1,
    dummyPrice: 1000,
  ),
  Product(
    id: 2,
    name: "Greek Pizza",
    price: 1500,
    image: "assets/images/Greek Pizza.jfif",
    Quantity: 1,
    dummyPrice: 1500,
  ),
  Product(
    id: 3,
    name: "Mushroom pizza",
    price: 1700,
    image: "assets/images/mushroom pizza.jpg",
    Quantity: 1,
    dummyPrice: 1700,
  ),
  Product(
    id: 4,
    name: "assets/images/margherita_pizza.jpg",
    price: 2000,
    image: "Margherita_pizza",
    Quantity: 1,
    dummyPrice: 2000,
  ),
  Product(
    id: 5,
    name: "Veggie Burger",
    price: 150,
    image: "assets/images/Supreme Veggie Burger.jpg",
    Quantity: 1,
    dummyPrice: 150,
  ),
  Product(
    id: 6,
    name: "Tomato Burger",
    price: 170,
    image: "assets/images/Lamb and Tomato Stuffed Burger.jpg",
    Quantity: 1,
    dummyPrice: 170,
  ),
  Product(
    id: 7,
    name: "Chilli burger",
    price: 150,
    image: "assets/images/Chilli burger With Pepper Relish.jpg",
    Quantity: 1,
    dummyPrice: 150,
  ),
  Product(
    id: 8,
    name: "pizza burger",
    price: 200,
    image: "assets/images/pizza burger.jpg",
    Quantity: 1,
    dummyPrice: 200,
  ),
  Product(
    id: 9,
    name: "Coca cola",
    price: 60,
    image: "assets/images/coca cola.jfif",
    Quantity: 1,
    dummyPrice: 60,
  ),
  Product(
    id: 10,
    name: "Coffee",
    price: 150,
    image: "assets/images/coffee.jfif",
    Quantity: 1,
    dummyPrice: 150,
  ),
  Product(
    id: 11,
    name: "Virgin mojito",
    price: 170,
    image: "assets/images/blackberry virgin mojito.jfif",
    Quantity: 1,
    dummyPrice: 170,
  ),
  Product(
    id: 12,
    name: "Cold coco",
    price: 200,
    image: "assets/images/cold coco.jpg",
    Quantity: 1,
    dummyPrice: 200,
  ),
  Product(
    id: 13,
    name: "Ketchup",
    price: 40,
    image: "assets/images/ketchup.jpg",
    Quantity: 1,
    dummyPrice: 40,
  ),
  Product(
    id: 14,
    name: "Mayonnaise",
    price:100,
    image: "assets/images/mayonnaise.jpg",
    Quantity: 1,
    dummyPrice: 100,
  ),
  Product(
    id: 15,
    name: "Italian dressing",
    price: 120,
    image: "assets/images/Italian dressing.jpg",
    Quantity: 1,
    dummyPrice: 120,
  ),
  Product(
    id: 16,
    name: "Hot sauces",
    price: 100,
    image: "assets/images/hot sauces.jpg",
    Quantity: 1,
    dummyPrice: 100,
  ),
  Product(
    id: 17,
    name: "Burger and frise",
    price: 100,
    image: "assets/images/burgerand frise.jfif",
    Quantity: 1,
    dummyPrice: 100,
  ),
  Product(
    id: 18,
    name: "4 pizza",
    price: 250,
    image: "assets/images/4pizza.webp",
    Quantity: 1,
    dummyPrice: 250,
  ),
  Product(
    id: 19,
    name: "assets/images/burger withfries,saucesand knife.jpg",
    price: 300,
    image: "combo 2",
    Quantity: 1,
    dummyPrice: 300,
  ),
  Product(
    id: 20,
    name: "Combo",
    price: 150,
    image: "assets/images/combo.jpg",
    Quantity: 1,
    dummyPrice: 150,
  ),
];